language: python

python:
  - "3.7"

sudo: required

before_install:
  - sudo apt-get python -m pip install
  - sudo apt-get python -m pip install openpyxl
  - sudo apt-get python -m pip install bs4

script:
  - python setup.py test