language: python

python:
  - "3.5.4"
  
install:
  - pip install coveralls
  - python3 -m pip install requests
  - python3 -m pip install bs4
  - python3 -m pip install openpyxl

script:
  - coverage run --source=Macrofitas setup.py test

after_success:
  - coveralls